from django.conf import settings
from metalayercore.outputs.classes import BaseOutput
from django.utils import feedgenerator
from datetime import datetime

class Output(BaseOutput):
    def get_unconfigured_config(self):
        return {
            'name':'atomoutput',
            'display_name_short':'ATOM',
            'display_name_long':'ATOM',
            'type':'url',
            'instructions':'note that action values like sentiment are not supported - use JSON for that!'
        }

    def generate_output(self, config, search_results):
        feed = feedgenerator.Atom1Feed(
            title='MetaLayer - Dashboard Feed',
            link='http://%s' % settings.SITE_HOST,
            description='ATOM Feed generated by the MataLayer Dashboard',
            feed_url=config['url']
        )
        for content in search_results['content_items']:
            feed.add_item(
                link = content['link'],
                title = content['title'],
                description = content['text'][0] if 'text' in content and len(content['text']) > 0 else None,
                author_name = content['author_display_name'] if 'author_display_name' in content else None,
                author_link = content['author_link'] if 'author_link' in content else None,
                pubdate = datetime.fromtimestamp(content['time']),
            )
        return feed.writeString('UTF-8'), 'application/rss+xml'
